### PR TITLE
Add the option to paginate the table component

### PR DESCRIPTION
**Pull request by makije**
Is this something you would be interested in?

In our application we have a pretty big list of items, that users can sort and filter, then export to csv.
So for performance reasons we like to only show a subset of the data, and let the user paginate through it, to verify be exporting to csv.

Let me know, what I can improve before a possible merge.
Don't know about the icon thing, I can leave that out, I just "fixed" it, since the icons was missing in my test environment.
Thanks!

### CODE REVIEW

**Comment by makije** [comment]
Ups, I see I commit'ed some new line changes, I can fix that before a possible merge.
A timeout make the tests fail, doesn't locally, again let me know if it have any interest.

**Comment by icarusion** [comment]
Recently developing 3.0 code, just conflicted, about page, i suggest use `Page` component

**Comment by makije** [comment]
I am using that as well, the Page component or any other means, tell the Table the size and which page to show.
I added it in the example for the table.

**Comment by makije** [comment]
It simply make the Table able to only render a subset of the table rows, not to kill the browser if there is say 5000 rows

**Comment by makije** [comment]
@icarusion just wanted to follow up, if you have had time to look at our suggestion in more detail, after my previous comments.

**Comment by icarusion** [comment]
Thank you for contributing code, but we have no plans to do so

**Pull request closed without merging**
