### PR TITLE
Updated Button's link processor logic

### PR DESCRIPTION
**Pull request by rijulg**
At present the URLs are being used in the buttons are directly rendering the parameter passed to "to", however in cases where the app is deployed under subfolders we provide a base to the vue-router and that base should be prefixed to the routes. 

This behavior already exists in vue-router, but since the theme does not use vue-router to resolve the links the links are not rendered correctly.

In this PR I have updated the function used to render the link so that it works across a multitude of cases:

1. Absolute URLs i.e. ones with http or https that always must contain // are sent back as it is
2. URLs are sent back as it is in case there is no vue router available
3. Vue router is used to resolve the URLs, the code is copied over from the source code of vue router. If the vue router resolver returns a valid route then we use that, otherwise we return the original URL

### CODE REVIEW

**Comment by rijulg** [comment]
Hey @icarusion,
Can you please take a look at this feature request and implementation.

**Comment by icarusion** [comment]
Thanks for your pr, will merge in 3.4.0 version.

**Comment by icarusion** [comment]
Hi, @rijulg , sorry review now, i have a problem that when should use `append` prop?

**Comment by icarusion** [comment]
already know that, merge it.

**Pull request merged**
