### PR TITLE
添加部分组件的types,后续继续更新中

### PR DESCRIPTION
**Pull request by yangdan8**

### CODE REVIEW

**Comment by yangdan8** [comment]
添加iview.d.ts

**Comment by ElderJames** [comment]
Well done

**Comment by leiserfg** [comment]
Merge it or move the code to https://github.com/DefinitelyTyped/iview

**Comment by lcx960324** [comment]
非常感谢您的代码，很抱歉现在才回复。
我会验证一下您的代码，确定无误后会合并此 PR。因为涉及到的内容非常多，请耐心等待一下。
再次感谢。

Thank you so much for your contribution. I'm so sorry for the late reply.
I'll check the code, make sure it works fine,  and then merge it.
Because this PR includes too much content, it'll take a while to check all the code. Please wait patiently.
Thank you again.

**Comment by hartmut-co-uk** [comment]
+1

**Comment by hartmut-co-uk** [comment]
Note: I manually brought in your types into my project to test.

Got compiler error `TS2708` when applying
`Vue.use(IView)`
so had to change file `index.d.ts` to 
```
export * from './iview'

import * as IView from './iview'
export default IView
```

and added (migrated from `index.d.ts`) `iview.d.ts` with
```
import Vue from "vue";

import { Affix } from "./affix";
import { Alert } from "./alert";
import { AutoComplete } from "./auto-complete";
import { Avatar } from "./avatar";
import { BackTop } from "./back-top";
import { Badge } from "./badge";
import { Breadcrumb, BreadcrumbItem } from "./breadcrumb";
import { Button, ButtonGroup } from "./button";
import { Card } from "./card";
import { Carousel } from "./carousel";
import { Cascader } from "./cascader";
import { Checkbox, CheckboxGroup } from "./checkbox";
import { Circle } from "./circle";
import { Collapse, CollapsePanel } from "./collapse";
import { ColorPicker } from "./color-picker";
import { DatePicker, DatePickerOptions } from "./date-picker";
import { Dropdown, DropdownItem } from "./dropdown";
import { Form, FormItem } from "./form";
import { GridRow, GridCol } from "./grid";
import { Icon } from "./icon";
import { Input } from "./input";
import { InputNumber } from "./input-number";
import { LoadingBarInstance, LoadingBarConfig } from "./loading-bar";
import { Menu, MenuItem, Submenu, MenuGroup } from "./menu";
import { MessageInstance, MessageConfig } from "./message";
import { Modal, ModalInstance, ModalConfig } from "./modal";
import { NoticeInstance, NoticeConfig, NoticeGlobalConfig } from "./notice";
import { Page } from "./page";
import { Poptip } from "./poptip";
import { Progress } from "./progress";
import { Radio, RadioGroup } from "./radio";
import { Rate } from "./rate";
import { Scroll } from "./scroll";
import { Select, SelectOption, SelectOptionGroup } from "./select";
import { Spin } from "./spin";
import { Steps, Step } from "./steps";
import { Switch } from "./switch";
import { Table, TableColumn, TableRenderCreateElementData, TableRenderCreateElementResult, TableColumnRenderParams, TableExportCsvParams } from "./table";
import { Tabs, TabPane } from "./tabs";
import { Tag } from "./tag";
import { Timeline, TimelineItem } from "./timeline";
import { TimePicker } from "./time-picker";
import { Tooltip } from "./tooltip";
import { Transfer } from "./transfer";
import { Tree, TreeChildren } from "./tree";
import { Upload } from "./upload";

export interface InstallationOptions {
  locale: any
}

/** The version of element-ui */
export const version: string

/**
 * Install all element-ui components into Vue.
 * Please do not invoke this method directly.
 * Call `Vue.use(ElementUI)` to install.
 */
export function install (vue: typeof Vue, options: InstallationOptions): void

export interface IAffix extends Affix { }
export interface IAlert extends Alert { }
export interface IAutoComplete extends AutoComplete { }
export interface IAvatar extends Avatar { }
export interface IBackTop extends BackTop { }
export interface IBadge extends Badge { }
export interface IBreadcrumb extends Breadcrumb { }
export interface IBreadcrumbItem extends BreadcrumbItem { }
export interface IButton extends Button { }
export interface IButtonGroup extends ButtonGroup { }
export interface ICard extends Card { }
export interface ICarousel extends Carousel { }
export interface ICascader extends Cascader { }
export interface ICheckbox extends Checkbox { }
export interface ICheckboxGroup extends CheckboxGroup { }
export interface ICircle extends Circle { }
export interface ICollapse extends Collapse { }
export interface ICollapsePanel extends CollapsePanel { }
export interface IColorPicker extends ColorPicker { }
export interface IDatePicker extends DatePicker { }
export interface IDatePickerOptions extends DatePickerOptions { }
export interface IDropdown extends Dropdown { }
export interface IDropdownItem extends DropdownItem { }
export interface IForm extends Form { }
export interface IFormItem extends FormItem { }
export interface IGridCol extends GridCol { }
export interface IGridRow extends GridRow { }
export interface IIcon extends Icon { }
export interface IInput extends Input { }
export interface IInputNumber extends InputNumber { }
export interface ILoadingBarConfig extends LoadingBarConfig { }
export interface ILoadingBarInstance extends LoadingBarInstance { }
export interface IMenu extends Menu { }
export interface IMenuGroup extends MenuGroup { }
export interface IMenuItem extends MenuItem { }
export interface IMessageConfig extends MessageConfig { }
export interface IMessageInstance extends MessageInstance { }
export interface IModal extends Modal { }
export interface IModalConfig extends ModalConfig { }
export interface IModalInstance extends ModalInstance { }
export interface INoticeConfig extends NoticeConfig { }
export interface INoticeGlobalConfig extends NoticeGlobalConfig { }
export interface INoticeInstance extends NoticeInstance { }
export interface IPage extends Page { }
export interface IPoptip extends Poptip { }
export interface IProgress extends Progress { }
export interface IRadio extends Radio { }
export interface IRadioGroup extends RadioGroup { }
export interface IRate extends Rate { }
export interface IScroll extends Scroll { }
export interface ISelect extends Select { }
export interface ISelectOption extends SelectOption { }
export interface ISelectOptionGroup extends SelectOptionGroup { }
export interface ISpin extends Spin { }
export interface IStep extends Step { }
export interface ISteps extends Steps { }
export interface ISubmenu extends Submenu { }
export interface ISwitch extends Switch { }
export interface ITable extends Table { }
export interface ITableColumn extends TableColumn { }
export interface ITableColumnRenderParams extends TableColumnRenderParams { }
export interface ITableExportCsvParams extends TableExportCsvParams { }
export interface ITableRenderCreateElementData extends TableRenderCreateElementData { }
export interface ITableRenderCreateElementResult extends TableRenderCreateElementResult { }
export interface ITabPane extends TabPane { }
export interface ITabs extends Tabs { }
export interface ITag extends Tag { }
export interface ITimeline extends Timeline { }
export interface ITimelineItem extends TimelineItem { }
export interface ITimePicker extends TimePicker { }
export interface ITooltip extends Tooltip { }
export interface ITransfer extends Transfer { }
export interface ITree extends Tree { }
export interface ITreeChildren extends TreeChildren { }
export interface IUpload extends Upload { }
```

I didn't really understand what I was doing :-), still though I'd leave a note...

**Comment by yangdan8** [comment]
解决全部插件中通过$on注册的事件没有在组件销毁时$off的bug,该bug可能导致大量内存泄漏

**Comment by lcx960324** [comment]
@yangdan8 看起来你的后续提交包含一些已经合并的代码， 麻烦处理下 ~

还有就是，麻烦一个 PR 只解决一个问题，非常感谢 ~

**Comment by hartmut-co-uk** [comment]
Hi @yangdan8 may I help on your fork?

General Note: I just noticed the `locale` needs type defs, too.

**Comment by hartmut-co-uk** [comment]
have locally added a very simple `iview/locale/index.d.ts`

```
declare module 'iview/dist/locale/*' {
  function locale (e: any): any;

  export default locale;
}
```

**Comment by sgf** [comment]
@yangdan8 https://github.com/yangdan8/iview
哥们，你这个目前能用嘛。。。。

**Comment by RDeluxe** [comment]
It would be so great to have working Typings for iview !

**Pull request closed without merging**
