### PR TITLE
Fix for table with children in columns

### PR DESCRIPTION
**Pull request by uzlov**
We have issues for table with children in header (issues after any change data in colums)
VM65566 vue.esm.js:592 [Vue warn]: You may have an infinite update loop in watcher with expression "columns"

### CODE REVIEW

**Comment by uzlov** [comment]
bug report https://github.com/iview/iview/issues/3762

**Comment by tangpingping** [comment]
I tried it according to your amendment and found that the problem was not solved and I didn't know what it was.

**Comment by tangpingping** [comment]
just modify <code>const colsWithId = this.makeColumnsId(this.columns);</code> into <code>const colsWithId = this.makeColumnsId(deepCopy(this.columns));</code>  is it right?

**Comment by tangpingping** [comment]
I have solved this problem, but only modified the life cycle of the updated data.

**Comment by h1orz** [comment]
@icarusion 数组重复引用导致多级表头Watcher无限循环的问题已经1个多月了，deepClone解决了重复引用的问题，一直没Pass...
难道都没人在用多级表头，动态生成么？

**Comment by miaoyuxinbaby** [comment]
https://github.com/iview/iview/issues/3472#issuecomment-408783325

这里有解决方案 @h1orz

**Comment by freddielovekqy** [comment]
根据上面的方法修改node_module/iview中的源码代码后不再出现页面卡死的问题，但是本地修改的node_module中的代码不会提交代码库，集成部署中取的还是公网中的iview源码，还是有问题的，这个问题有官方的解决方案吗？
After modifying the source code in node_module/iview according to the above method, there will be no page crash problem, but the code in locally modified node_module will not submit the code base. The iView source code in public network is still taken in the integration deployment. Is there an official solution to this problem?

**Pull request closed without merging**
