### PR TITLE
fix bug:#4073

### PR DESCRIPTION
**Pull request by iLinhao**

### CODE REVIEW

**Comment by icarusion** [comment]
Hi, @SergioCrisostomo could you review this pr?

**Review by SergioCrisostomo — APPROVED** [review]
👍

**Comment by icarusion** [comment]
@ILINGHO I test this pr, but the problem still exists

**Comment by iLinhao** [comment]
@icarusion Could you please tell me your test steps？
line 359: let hasDefaultSelected = slotOptions.some(option => this.query === option.key);
hasDefaultSelected always false，this.query should compare with option.label

**Comment by icarusion** [comment]
@ILINGHO just use this issue's demo https://github.com/iview/iview/issues/4073 and run in its steps

**Comment by iLinhao** [comment]
@icarusion Ok，I'll check it later.

**Pull request closed without merging**
