### PR TITLE
Select组件，下拉选项显示问题

### PR DESCRIPTION
**Pull request by trevorHsu**
[修复Bug]: 对于Select组件，在filterable状态下，若输入框内容不为空，则当下拉选项的数据改变时，组件将无法正常显示下拉选项。
[fixed Bug]: For Select component, when using the prop "filterable" and the input box was not empty, select options can not be showed normally after the change of options data.

### CODE REVIEW

**Comment by icarusion** [comment]
Please clean the pr first, and provide an online example of issue

**Comment by hsroad** [comment]
[fixed Bug]: For Select component, when using the prop "filterable" and the input box was not empty, select options can not be showed normally after the change of options data.

**Comment by hsroad** [comment]
[fixed Bug]: For Select component, when using the prop "filterable" and the input box was not empty, select options can not be showed normally after the change of options data.

**Comment by hsroad** [comment]
[fixed Bug]: For Select component, when using the prop "filterable" and the input box was not empty, select options can not be showed normally after the change of options data.

**Pull request closed without merging**
