### PR TITLE
修复table里嵌套table报 Cannot read property 'width' of undefined"的错误

### PR DESCRIPTION
**Pull request by chjtx**
table里的td再创建个table会报以下错误，已测试过
>[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'width' of undefined"

### CODE REVIEW

**Comment by SergioCrisostomo** [comment]
@chjtx good catch 👍 

It would be nice to refactor also `querySelectorAll` and use `children`, so we would have:

    const $td = this.$refs.tbody.$el.querySelector('tbody tr').children;

**Comment by SergioCrisostomo** [comment]
@chjtx one more thing: I was looking better at the code and am not sure of the bug creating this warning. Could you make a jsFiddle or codepen reproducing the problem? 

Thanks!

**Comment by icarusion** [comment]
Table in Table, it looks a little complicated. I recommend using `type: 'expand'`

**Comment by chjtx** [comment]
@SergioCrisostomo my code like follow

```html
<Table :height="height" border :columns="columns" :data="orders"></Table>
```
```js
export default {
  data() {
    return {
      columns: [{
        render: function (h, params) {
          return h('Poptip', {
            props: {
              trigger: 'hover',
              placement: 'right'
            }
          }, [h('div', {
            slot: 'content'
          }, [
            h('Table', { // sub table is here
              props: {
                columns: ...
              }
            })
          ])])
        }
      }]
    }
  }
}
```

and the effect is as follow：

**Comment by SergioCrisostomo** [comment]
@chjtx thank you. I see your problem now:
https://codepen.io/sergiocrisostomo/pen/YrGVzX

Could you please change the fix to:

    const $td = this.$refs.tbody.$el.querySelector('tbody tr').children;

That makes the code more clear and safe, since `.childNodes` [also catches `<!-- -->` node comments](https://jsfiddle.net/Sergio_fiddle/0tk6s850/).

**Comment by chjtx** [comment]
@SergioCrisostomo thank you! i do it.

**Comment by icarusion** [comment]
Thanks!

**Pull request merged**
