### PR TITLE
Select: Keyboard navigation like native

### PR DESCRIPTION
**Pull request by Xotic750**
To get the keyboard controls working with all use cases a refactor is required.

https://github.com/iview/iview/issues/1647

### CODE REVIEW

**Comment by SergioCrisostomo** [comment]
Closes #1614
Closes #2329

**Comment by Xotic750** [comment]
Requires https://github.com/iview/iview/pull/3077

**Comment by icarusion** [comment]
# 1 
can not open other Select when one is opened, should click twice:
http://7u2ka3.com1.z0.glb.clouddn.com/iview-issue/select1.gif

# 2
in remove search, when search something, and press `enter`, the dropdown will hide, diff:
`old`: http://7u2ka3.com1.z0.glb.clouddn.com/iview-issue/select2.gif
`now`: http://7u2ka3.com1.z0.glb.clouddn.com/iview-issue/select3.gif
code here:
```vue
<template>
    <Select
        v-model="model14"
        multiple
        filterable
        remote
        :remote-method="remoteMethod2"
        :loading="loading2">
        <Option v-for="(option, index) in options2" :value="option.value" :key="index">{{option.label}}</Option>
    </Select>
</template>
<script>
    export default {
        data () {
            return {
                model14: [],
                loading2: false,
                options2: [],
                list: ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New hampshire', 'New jersey', 'New mexico', 'New york', 'North carolina', 'North dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode island', 'South carolina', 'South dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West virginia', 'Wisconsin', 'Wyoming']
            }
        },
        methods: {
            remoteMethod2 (query) {
                if (query !== '') {
                    this.loading2 = true;
                    setTimeout(() => {
                        this.loading2 = false;
                        const list = this.list.map(item => {
                            return {
                                value: item,
                                label: item
                            };
                        });
                        this.options2 = list.filter(item => item.label.toLowerCase().indexOf(query.toLowerCase()) > -1);
                    }, 200);
                } else {
                    this.options2 = [];
                }
            }
        }
    }
</script>

```
# 3
`AutoComplete` component is based on `Select`, now it will throw errors, like:
```vue
<template>
    <AutoComplete
        v-model="value1"
        :data="data1"
        @on-search="handleSearch1"
        placeholder="input here"
        style="width:200px"></AutoComplete>
</template>
<script>
    export default {
        data () {
            return {
                value1: '',
                data1: []
            }
        },
        methods: {
            handleSearch1 (value) {
                this.data1 = !value ? [] : [
                    value,
                    value + value,
                    value + value + value
                ];
            }
        }
    }
</script>

```

# 4

**Comment by icarusion** [comment]
# 4
in remote search, code like # 3, when focus input, and press `down`, dropdown will flash:
http://7u2ka3.com1.z0.glb.clouddn.com/iview-issue/select4.gif

# 5
Select in remote and multiple mode, and when the data is cleared, the selected item is not empty. closes #2066 
http://7u2ka3.com1.z0.glb.clouddn.com/iview-issue/select5.gif
code:
```vue
<template>
    <div>
        {{ model13 }}
        <Select
                v-model="model13"
                filterable
                remote
                :remote-method="remoteMethod1"
                :loading="loading1">
            <Option v-for="(option, index) in options1" :value="option.value" :key="index">{{option.label}}</Option>
        </Select>
        <Button @click="model13 = []">clear</Button>
    </div>
</template>
<script>
    export default {
        data () {
            return {
                model13: '',
                loading1: false,
                options1: [],
                list: ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New hampshire', 'New jersey', 'New mexico', 'New york', 'North carolina', 'North dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode island', 'South carolina', 'South dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West virginia', 'Wisconsin', 'Wyoming']
            }
        },
        methods: {
            remoteMethod1 (query) {
                if (query !== '') {
                    this.loading1 = true;
                    setTimeout(() => {
                        this.loading1 = false;
                        const list = this.list.map(item => {
                            return {
                                value: item,
                                label: item
                            };
                        });
                        this.options1 = list.filter(item => item.label.toLowerCase().indexOf(query.toLowerCase()) > -1);
                    }, 200);
                } else {
                    this.options1 = [];
                }
            }
        }
    }
</script>
```

# 6
in search and remote search now, when select an item, focus again, the input should be selected:
`old`:
image
`now`:
image

**Comment by Xotic750** [comment]
1 - [ ] Leave as is.
2 - [ ]  Needs fixing.
3 - [ ] Needs testing and fixing against the provided example.
4 - [ ] Needs fixing.
5 - [ ] Needs testing and possibly fixing.
6 - [ ] Revert to old way rather than new more native way.

**Comment by icarusion** [comment]
# 7
about No 2, i find another problem, when select some item, and focused, than, press `delete` key, the dropdown flash:
http://7u2ka3.com1.z0.glb.clouddn.com/iview-issue/select7.gif

**Comment by icarusion** [comment]
in commit https://github.com/iview/iview/commit/1112eb1 ,No2 problem seems to exist

**Comment by Xotic750** [comment]
Yes, focus is required for keyboard support. Thanks for pointing to it, I am working on solving the issues.

**Comment by icarusion** [comment]
No.2 has been fixed.

**Comment by Xotic750** [comment]
FROZEN! DO NOT PULL!

**Comment by Xotic750** [comment]
See refactor https://github.com/iview/iview/pull/3157

**Pull request closed without merging**
