### PR TITLE
解决select 默认数据不能绑定0的情况 

### PR DESCRIPTION
**Pull request by luffyzhao**
fixes [3696](https://github.com/iview/iview/issues/3696)

### CODE REVIEW

**Comment by luffyzhao** [comment]
不知道应该用哪个版本的eslint-plugin-vue 本地老是有点问题。 不过 npm run unit 可以过。。先提交让travis-ci帮忙test一下

**Comment by luffyzhao** [comment]
fixes [3696](https://github.com/iview/iview/issues/3696)

**Comment by SergioCrisostomo** [comment]
@luffyzhao thank you for the fix! Good catch 👍 

Please remove the `package-lock.json` from the PR so we can merge this.

**Comment by luffyzhao** [comment]
@SergioCrisostomo  Is that so?

**Comment by icarusion** [comment]
Thanks @luffyzhao and @SergioCrisostomo ,will check and merge soon

**Pull request merged**
