### PR TITLE
Fix gutter of tabs bar

### PR DESCRIPTION
**Pull request by hfm-an**
When i set style of  `.ivu-tabs-tab` from `margin-right: 16px` to `margin-right: 60px`, bar's location is wrong.

### CODE REVIEW

**Comment by icarusion** [comment]
Please provide a demo by jsfiddle or https://run.iviewui.com/

**Comment by hfm-an** [comment]
https://run.iviewui.com/phh68DUc

**Comment by icarusion** [comment]
Suggest to use like this: https://run.iviewui.com/Djdfm1VC

**Comment by hfm-an** [comment]
I think it's fine for some scenarios. But use `padding` will affect width of the bar. 
The distance between `tabs` is coupled to the length of bar.

The code in tabs.vue on line 200 :

```js
const gutter = this.size === 'small' ? 0 : 16;
```

It cause that users can't reset the value of `margin-right`.

Anyway, thank you for your reply.

**Pull request closed without merging**
