### PR TITLE
[feature request] #3799 implement table component columns filters sup…

### PR DESCRIPTION
**Pull request by m430**
I add render function support for table columns filters item. user can use it to custom any template for himself. All test case is passed. please check.

### CODE REVIEW

**Comment by m430** [comment]
hi @icarusion , I saw your 3.0 plan, I'm very interesting for that, can i join the @iview organization to do somthing for it together?

**Comment by icarusion** [comment]
Of course yes, please wechat me: icarusion

**Comment by icarusion** [comment]
Table will refactor in the future, so we don't want to spend much time on it now.

**Comment by m430** [comment]
Ok, I will close my PR. thanks for your notice.

**Pull request closed without merging**
