### PR TITLE
Create fa_FA.js

### PR DESCRIPTION
**Pull request by tomvolek**
Translation for Farsi

### CODE REVIEW

**Comment by icarusion** [comment]
Hi, thanks for your pr, but there are some mistakes, can you refer to other language packs to fix it?

**Comment by SergioCrisostomo** [comment]
@tomvolek could you check this folder https://github.com/iview/iview/tree/2.0/src/locale/lang and just add a new `.js` file with a plain object, no webpack.

Thank you!

**Comment by icarusion** [comment]
I will close this pr for a long time. If there is any update later, You can create a new pr. Thank you

**Comment by SergioCrisostomo** [comment]
@tomvolek could you send a new PR for this? Would be great to have Farsi language file!

Cheers,
Sérgio

**Comment by tomvolek** [comment]
Sergio:   sorry I missed your comments here earlier, what do you men by "add a new .js file with a plain object, no webpack".  Please direct me what to do and be glad to do it . 

Tom

**Comment by SergioCrisostomo** [comment]
@tomvolek you can copy this file: https://github.com/iview/iview/blob/2.0/src/locale/lang/en-US.js rename it to `fa_FA.js` and change the contents. It should look like this english one but Farsi instead.

Thanks!

**Pull request closed without merging**
